-- Hotkey/spawn behavior is implemented in MD (md/casino.xml)
-- via the Hotkey API and create_ship actions.
--
-- Intentionally left empty to avoid using non-existent Lua APIs like
-- Input.contextActive / MD.Signal for ship spawning.
